version: '3.9'
services:
  node:
    build:
      context: .
    environment:
      DATABASE_PASSWORD: test
      DATABASE_NAME: test
      DATABASE_USERNAME: test
      DATABASE_HOST: mysql
    ports:
      - 3000:3000
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 3306:3306
      